### PR TITLE
Bump to postcss 8

### PR DESCRIPTION
**Pull request by charlessuh**

### CODE REVIEW

**Review by bmatcuk — APPROVED** [review]
Hi @charlessuh, thanks for the PR! Sorry it took a while to get to it. Looks good to me, though, typescript fails to compile `lib/parser.ts` because the `Processor` type is no longer exported from `postcss`. I fixed that and will merge your changes.

**Comment by bmatcuk** [comment]
I released v2.0.0 that contains your PR.

**Comment by charlessuh** [comment]
Awesome, no problemo!

FYI, it looks like the `Processor` issue only happens if you use the latest released version of postcss, and the next version should have a fix: https://github.com/postcss/postcss/issues/1666

**Comment by bmatcuk** [comment]
Cool, thanks for the heads up!

**Pull request merged**
